apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: application-manager-production

namespace: application-manager

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/configmap-patch.yaml
  - path: patches/hpa-patch.yaml

images:
  - name: application-manager-service
    newName: ghcr.io/your-org/application-manager-service
    newTag: "1.1.0"
