apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: application-manager-base

namespace: application-manager

labels:
  - includeSelectors: true
    pairs:
      app: application-manager
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: application-manager-service

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: application-manager-service
    newTag: "1.1.0"
