apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: application-manager
  labels:
    app.kubernetes.io/name: application-manager
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application-manager
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: application-worker
  labels:
    app.kubernetes.io/name: application-manager
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application-manager
      app.kubernetes.io/component: worker
