apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: application-manager-staging

namespace: application-manager-staging

resources:
  - ../../base

nameSuffix: -staging

patches:
  - path: patches/configmap-patch.yaml

replicas:
  - name: application-manager
    count: 2
  - name: application-worker
    count: 2

images:
  - name: application-manager-service
    newTag: staging
